# Generated by Django 6.0.3 on 2026-04-07 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pais_alter_cliente_options_cliente_pais_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='naciminto',
            field=models.DateField(null=True),
        ),
    ]
